parameters:
#    users_adminuser.example.class: Users\AdminuserBundle\Example

services:
#    users_adminuser.example:
#        class: %users_adminuser.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
