<?php

namespace Users\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BackgroundslideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BackgroundslideRepository extends EntityRepository
{
}
