produit_service_contact_us:
    path: /nous/contacter
    controller: App\Controller\Produit\Service\MessageController::contactus
produit_service_apropos_denous:
    path: /info/azcorp/{position}/{idtype}/{idart}/{page}
    controller: App\Controller\Produit\Service\ServiceController::aproposdenous
    defaults:
        idtype: 0
        idart: 0
        page: 1
    requirements:
        idtype: \d+
        idart: \d+
        page: \d+
produit_service_assistance_entreprise:
    path: /assistance/entreprise/{entreprise}
    controller: App\Controller\Produit\Service\MessageController::assistanceentreprise
    defaults:
        entreprise: 1
    requirements:
        entreprise: \d+
produit_service_visiter_notre_blog:
    path: /offres/speciales/{id}/{page}
    controller: App\Controller\Produit\Service\ServiceController::notreblog
    defaults:
        id: 0
        page: 1  
    requirements:
        id: \d+
        page: \d+
produit_service_az_evenements:
    path: /evenements/az/{id}/{page}
    controller: App\Controller\Produit\Service\ServiceController::evenements
    defaults:
        id: 0
        page: 1
    requirements:
        id: \d+
        page: \d+
produit_service_yourcv_recrutement:
    path: /azcorp/careers/{stage}
    controller: App\Controller\Produit\Service\RecrutementController::votredossier
    defaults:
        stage: 0
produit_service_dossier_derecrutement_user:
    path: /dossier/user/pour/recrutement/lancer
    controller: App\Controller\Produit\Service\RecrutementController::ajoutdossieruser
produit_service_key_of_product_authentification:
    path: /key/of/product/authentification
    controller: App\Controller\Produit\Service\CurentwebsiteController::curentwebsite
produit_service_affiche_contenu_detaille_article_blog:
    path: /affiche/contenu/detaill/article/blog/{id}
    controller: App\Controller\Produit\Service\ServiceController::affichearticle
    requirements:
        id: \d+
produit_service_ajouter_commentaire_article_user:
    path: /ajouter/commentaire/article/{id}
    controller: App\Controller\Produit\Service\ServiceController::ajoutercommentaire
    requirements:
        id: \d+
produit_service_supprimer_commentaire_courant_article:
    path: /supprimer/commentaire/courant/article/{id}
    controller: App\Controller\Produit\Service\ServiceController::supprimercommentaire
    requirements:
        id: \d+
produit_service_detail_article_support:
    path: /detail/article/support/{position}
    controller: App\Controller\Produit\Service\ServiceController::detailarticlesupport
    defaults:
        position: 'article'
users_adminuser_telecharg_cv_user:
    path: /telecharge/doc/fichier/prog/{id}
    controller: App\Controller\Produit\Service\RecrutementController::telechargercv
    requirements:
        id: \d+
users_adminuser_telecharg_lettre_motivation_user:
    path: /telecharge/doc/image/programme/{id}
    controller: App\Controller\Produit\Service\RecrutementController::telechargerlettre
    requirements:
        id: \d+
produit_service_detail_actualite:
    path: /details/actualite/{id}
    controller: App\Controller\Produit\Service\ServiceController::detailactualite
    requirements:
        id: \d+