<?php

namespace App\Repository\Users\User;

use Doctrine\ORM\EntityRepository;

/**
 * ReponsebilletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponsebilletRepository extends EntityRepository
{
}
