<?php

namespace Produit\ProduitBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CaracteristiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaracteristiqueRepository extends EntityRepository
{
public function getSelectList()
{
	$qb = $this->createQueryBuilder('c')
				  ->orderBy('c.nom','ASC');
	return $qb;
}
	
public function myFindList($rang, $limit)
{
	$query = $this->createQueryBuilder('c')
	              ->leftJoin('c.souscategorie','s')
				  ->addSelect('s')
				  ->where('s.rang = :rang')
				  ->setParameter('rang',$rang)
	              ->orderBy('c.rang','ASC')
                  ->getQuery();
	return $query->getResult();
}
}
