<?php

namespace Produit\ProduitBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CataloguechantierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CataloguechantierRepository extends EntityRepository
{
public function getSelectList()
{
    $qb = $this->createQueryBuilder('c')
                  ->orderBy('c.nom','ASC');
	return $qb;
}
public function myfindAll()
{
	$query = $this->createQueryBuilder('c')
	              ->orderBy('c.rang','ASC')
                  ->getQuery();
	return $query->getResult();
}
}
