<?php

namespace App\Repository\Produit\Service;

use Doctrine\ORM\EntityRepository;

/**
 * CommentaireblogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireblogRepository extends EntityRepository
{
}
