<?php

namespace Users\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImgslideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImgslideRepository extends EntityRepository
{
public function myFindAll()
{
	$query = $this->createQueryBuilder('i')
	              ->leftJoin('i.souscategorie','s')
				  ->addSelect('s')
	              ->orderBy('i.rang','ASC')
                  ->getQuery();
	return $query->getResult();
}

public function myFindAcceuil()
{
	$query = $this->createQueryBuilder('i')
	              ->leftJoin('i.souscategorie','s')
				  ->addSelect('s')
				  ->where('i.slide = 1')
	              ->orderBy('i.rang','ASC')
                  ->getQuery();
	return $query->getResult();
}
}
