<?php

namespace Produit\ServiceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieappliRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieappliRepository extends EntityRepository
{
public function myFindAll()
{
	$query = $this->createQueryBuilder('c')
	              ->leftJoin('c.applications','a')
				  ->addSelect('a')
	              ->orderBy('c.rang','ASC')
                  ->getQuery();
	return $query->getResult();
}
}
