<?php

namespace Produit\ServiceBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CouponcardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouponcardRepository extends EntityRepository
{
public function myCouponPagine($page, $nombreParPage)
{
	if ($page < 1){
	throw new \InvalidArgumentException('Page inexistant');
	}
	$query = $this->createQueryBuilder('c')
	              ->orderBy('c.date','DESC')
                  ->getQuery();
	$query->setFirstResult(($page-1) * $nombreParPage)
		  ->setMaxResults($nombreParPage);
	return new Paginator($query);
}
}
