<?php

namespace Produit\ServiceBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * PaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaysRepository extends EntityRepository
{
public function myfindAll()
{
	$query = $this->createQueryBuilder('p')
	              ->orderBy('p.nom','ASC')
                  ->getQuery();
	return $query->getResult();
}

public function getSelectList()
{
	$qb = $this->createQueryBuilder('p')
               ->orderBy('p.nom','ASC');
	return $qb;
}
public function findPaysPagine($page, $nombreParPage)
{
	if($page < 1){
		throw new \InvalidArgumentException('Page inexistant');
	}
	$query = $this->createQueryBuilder('p')
	              ->orderBy('p.nom','ASC')
                  ->getQuery();
	$query->setFirstResult(($page-1) * $nombreParPage)
		  ->setMaxResults($nombreParPage);
	return new Paginator($query);
}
}
