<?php

namespace App\Repository\Produit\Produit;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends EntityRepository
{
public function myFindAll()
{
	$query = $this->createQueryBuilder('c')
	              ->leftJoin('c.souscategories','s')
				  ->addSelect('s')
	              ->orderBy('c.date','ASC')
                  ->getQuery();
	return $query->getResult();
}

public function myTypeFormation($nbre)
{
	$query = $this->createQueryBuilder('c')
				  ->where('c.typeservice LIKE :n')
				  ->orWhere('c.typeservice LIKE :m')
				  ->setParameter('n','%continue%')
				  ->setParameter('m','%diplomante%')
                  ->orderBy('c.rang', 'ASC')
				  ->setMaxResults($nbre)
                  ->getQuery();
return $query->getResult();
}
}
