twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        site: AZ CORPORATION 
        metier: Produits et services Informatiques
        devise: FCFA
        ville: Yaounde
        telephone: +237 676264027
        telwath: +237 676264027
        facebook: AZCorpAfrica
        twitter: #
        google: #
        linkedin: 
        slogan: La solution Informatique dont vous avez besoin
        description: AZ Corporation est une sociétés de services en Ingénierie Informatique 
        localisation: BP 30020 YAOUNDE CAMEROUN, BYEMASSI-BAMBIS 
        email: infos@azcorporation.com
        mailregex: /[a-z0-9._-]+@[a-z0-9._-]{2,}\.[a-z]{2,4}/i
        siteweb: http://afex.com

when@test:
    twig:
        strict_variables: true
