<?php

namespace App\Repository\Produit\Service;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends EntityRepository
{
public function myFindAll()
{
	$query = $this->createQueryBuilder('a')
	              ->leftJoin('a.categorieappli','c')
				  ->addSelect('c')
	              ->orderBy('a.rang','ASC')
                  ->getQuery();
	return $query->getResult();
}
}
