<?php

namespace App\Repository\Produit\Service;

use Doctrine\ORM\EntityRepository;

/**
 * RecrutementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecrutementRepository extends EntityRepository
{
public function myfindAll()
{
	$query = $this->createQueryBuilder('r')
	              ->orderBy('r.date','DESC')
                  ->getQuery();
	return $query->getResult();
}

public function findPublicSupport()
{
	$query = $this->createQueryBuilder('r')
				  ->where('r.typedocument LIKE :n')
				  ->orWhere('r.typedocument LIKE :m')
				  ->setParameter('n','%depliant%')
				  ->setParameter('m','%planing%')
	              ->orderBy('r.date','DESC')
                  ->getQuery();
	return $query->getResult();
}

public function findSupportByType($type)
{
	$query = $this->createQueryBuilder('r')
			      ->where('r.typedocument LIKE :n')
	              ->orderBy('r.date','DESC')
				  ->setParameter('n','%'.$type.'%')
                  ->getQuery();
	return $query->getResult();
}
}
