<?php

namespace App\Repository\Produit\Service;

use Doctrine\ORM\EntityRepository;

/**
 * TypearticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypearticleRepository extends EntityRepository
{
public function findTypeService()
{
	$query = $this->createQueryBuilder('t')
	              ->leftJoin('t.services','s')
				  ->addSelect('s')
	              ->where('s.typearticle LIKE :ab')
	              ->orWhere('s.typearticle LIKE :ev')
	              ->orWhere('s.typearticle LIKE :act')
	              ->orWhere('s.typearticle LIKE :dem')
	              ->orWhere('s.typearticle LIKE :tem')
				  ->setParameter('ab','%aproposinstitut%')
				  ->setParameter('ev','%evenement%')
				  ->setParameter('act','%actualite%')
				  ->setParameter('dem','%demarcheaz%')
				  ->setParameter('tem','%temoignage%')
                  ->orderBy('t.rang', 'ASC')
                  ->getQuery();
	return $query->getResult();
}
}
