parameters:
#    produit_produit.example.class: Produit\ProduitBundle\Example

services:
#    produit_produit.example:
#        class: %produit_produit.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
