<?php

namespace Produit\ProduitBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChapitrecoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChapitrecoursRepository extends EntityRepository
{
public function listechapitrecours($id)
{
	$query = $this->createQueryBuilder('c')
	              ->leftJoin('c.partiecours','p')
	              ->leftJoin('p.produit','d')
				  ->addSelect('p')
				  ->addSelect('d')
				  ->where('d.id = :id')
				  ->setParameter('id',$id)
	              ->orderBy('d.rang','ASC')
                  ->getQuery();
	return $query->getResult();
}

public function chapitreselectcours($id)
{
	$query = $this->createQueryBuilder('c')
	              ->leftJoin('c.partiecours','p')
	              ->leftJoin('p.produit','d')
				  ->addSelect('p')
				  ->addSelect('d')
				  ->where('d.id = :id AND c.type != 1')
				  ->setParameter('id',$id)
	              ->orderBy('d.rang','ASC')
                  ->getQuery();
	return $query->getResult();
}
}
