<?php

namespace Produit\ProduitBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VideochapitreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideochapitreRepository extends EntityRepository
{
}
