<?php

namespace App\Repository\Produit\Produit;

use Doctrine\ORM\EntityRepository;

/**
 * SouscategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SouscategorieRepository extends EntityRepository
{
public function getSelectList($id)
{
    $qb = $this->createQueryBuilder('s')
	              ->leftJoin('s.categorie', 'c')
                  ->where('c.id = :id')
                  ->setParameter('id', $id)
                  ->orderBy('s.nom','ASC');
	return $qb;
}

public function topsouscategorieAlter($type='',$nbre=10)
{
	$query = $this->createQueryBuilder('s')
				  ->leftJoin('s.categorie', 'c')
				  ->addSelect('c')
				  ->where('c.typeservice NOT LIKE :n')
				  ->setParameter('n','%'.$type.'%')
                  ->orderBy('c.rang', 'ASC')
				  ->setMaxResults($nbre)
                  ->getQuery();
return $query->getResult();
}

public function topsouscategorie($type='',$nbre=10)
{
	$query = $this->createQueryBuilder('s')
				  ->leftJoin('s.categorie', 'c')
				  ->addSelect('c')
				  ->where('c.typeservice LIKE :n')
				  ->setParameter('n','%'.$type.'%')
                  ->orderBy('c.rang', 'ASC')
				  ->setMaxResults($nbre)
                  ->getQuery();
return $query->getResult();
}
}
